version: "3"
services:
  sql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soft-q-learning
    entrypoint: tail -f /dev/null
    volumes:
      - .:/root/sql
      - ${MUJOCO_LICENSE_PATH:-./.mujoco/mjkey.txt}:/root/rllab/vendor/mujoco/mjkey.txt
    environment:
      MUJOCO_PY_MJKEY_PATH: /root/rllab/vendor/mujoco/mjkey.txt
  lsp-sandbox:
    image: gcr.io/tensorflow/tensorflow:1.4.1-py3
    container_name: sac-lsp
    ports:
      - "8888:8888"
    expose:
      - "8888"
    volumes:
      - ./:/sac
    command: jupyter notebook --notebook-dir=/sac --allow-root
