name: sac-ray
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.5
- pip:
  - absl-py==0.2.0
  - astor==0.6.2
  - attrs==17.4.0
  - awscli==1.14.23
  - baselines==0.1.4
  - bleach==1.5.0
  - boto3==1.7.4
  - botocore==1.10.4
  - cached-property==1.4.2
  - chardet==3.0.4
  - click==6.7
  - colorama==0.3.7
  - cryptography==2.2.2
  - cycler==0.10.0
  - cython==0.28.2
  - docutils==0.14
  - flatbuffers==2015.12.22.1
  - funcsigs==1.0.2
  - future==0.16.0
  - gast==0.2.0
  - google-api-python-client==1.6.7
  - grpcio==1.11.0
  - gtimer==1.0.0b5
  - gym==0.9.7
  - html5lib==0.9999999
  - idna==2.6
  - jmespath==0.9.3
  - joblib==0.11
  - kiwisolver==1.0.1
  - mako==1.0.7
  - markdown==2.6.11
  - markupsafe==1.0
  - matplotlib==2.2.2
  - more-itertools==4.1.0
  - numpy==1.14.3
  - path.py==11.0.1
  - pluggy==0.6.0
  - protobuf==3.5.2.post1
  - psutil==5.4.3
  - py==1.5.3
  - pyasn1==0.4.2
  - pyglet==1.3.1
  - pyopengl==3.1.0
  - pyparsing==2.2.0
  - pytest==3.5.0
  - python-dateutil==2.6.1
  - pytz==2018.4
  - pyyaml==3.12
  - "git+git://github.com/hartikainen/ray.git@79c0c192f8e4c5008cd2a3ecee47af6be5b3cd36#subdirectory=python"
  - redis==2.10.6
  - requests==2.18.4
  - rsa==3.4.2
  - s3transfer==0.1.12
  - scipy==1.0.1
  - six==1.11.0
  - tensorboard==1.8.0
  - tensorflow==1.8.0
  - termcolor==1.1.0
  - theano==1.0.1
  - urllib3==1.22
  - werkzeug==0.14.1
